[root@undercloud ~]# history 
    1  init 0
    2  tail -f /var/log/secure 
    3  yum repolist
    4  hostnamectl set-hostname undercloud.example.com
    5  ifco
    6  ip a s
    7  ifup eth1
    8  subscription-manager register
    9  subscription-manager list -all
   10  subscription-manager list -all --available
   11  subscription-manager list --all --available
   12  subscription-manager attach --pool=8a85f98160e6119c0160e901f57f767f
   13  sudo subscription-manager repos --disable=* 
   14  useradd stack
   15  echo 'r3dh4t1!' | passwd --stdin stack
   16  echo "stack ALL=(root) NOPASSWD:ALL" | tee -a /etc/sudoers.d/stack
   17  chmod 0440 /etc/sudoers.d/stack
   18          sudo subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms
   19  yum install @'@Server with GUI'
   20  yum install @'Server with GUI'
   21  yum install '@Server with GUI'
   22  yum groupinstall 'Server with GUI'
   23  yum install         libguestfs         libguestfs-tools         libvirt-client         libvirt         libvirt-python         qemu-guest-agent         qemu-img         qemu-kvm         virt-install         virt-manager \      
   24  yum update -y
   25  reboot 
   26  history 






---
- name: Configuración de Equipo
  hosts: oracle
  remote_user: root
  vars:
    - redhatpass: "$6$lf92fiDijp1G.mK6$plOZCrslpetoybLUIhs5jgfx2OqTvnl93/Tz0KgJavQtQq4u9TJJtYTzZmwu2Xi4oFy1S.MvjaRw.VU.r0fId/"
  tasks:
    - name: Install all my packages
      yum: name='@Server with GUI' state=lastest
      
    - name: Instalando paquetes para Oracle.
      yum: pkg={{item}} state=installed
      with_items:
        - tigervnc-server
        - xorg-x11-fonts-Type1
    - name: Creando usuario Red Hat.
      user:
        name: redhat
        password: '{{ redhatpass }}'
        
    - copy:
        src: /lib/systemd/system/vncserver@.service
        dest: /etc/systemd/system/vncserver@:3.service
        owner: oracle
        remote_src: yes
        
        #firewall-cmd --permanent --zone=public --add-port=5903/tcp
        #firewall-cmd --reload
        
        systemctl daemon-reload
        systemctl start vncserver@:3.service
        systemctl enable vncserver@:3.service
        
        subscription-manager register
        subscription-manager attach --pool=8a85f9815dbd9297015dbdb8186b428d 
        sudo subscription-manager repos --disable=* 
        sudo subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms
        yum update -y
        
        yum install \
        libguestfs \
        libguestfs-tools \
        libvirt-client \
        libvirt \
        libvirt-python \
        qemu-guest-agent \
        qemu-img \
        qemu-kvm \
        virt-install \
        virt-manager \      
        virt-viewer \
        virt-who \
        spice-vdagent \
        targetcli \
        
        cd /root/
        wget https://raw.githubusercontent.com/chipotez/director-12/master/setup-env.sh
        chmod 755 setup-env.sh
        ./setup-env.sh
        
        virsh  list --all
        virsh start undercloud
        echo -e "192.168.0.253\t\tundercloud.redhat.local\tundercloud" >> /etc/hosts        
        ssh undercloud
        
        [undercloud]
          ip a s
          exit
        
        [KVM - Server]
        useradd stck
        echo 'r3dh4t1!' | passwd --stdin stack
        ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -q -N ""
        mkdir ~stack/.ssh
scp ~/.ssh/id_ed25519.pub ~stack/.ssh/authorized_keys
chmod 0700 ~stack/.ssh
chmod 0400 ~stack/.ssh/authorized_keys
chown -R stack:stack ~stack/.ssh
restorecon -rv ~stack/.ssh


cat << EOF > /etc/polkit-1/localauthority/50-local.d/50-libvirt-user-stack.pkla
[libvirt Management Access]
Identity=unix-user:stack
Action=org.libvirt.unix.manage
ResultAny=yes
ResultInactive=yes
ResultActive=yes
EOF

virsh snapshot-create-as undercloud undercloud-snap-lab0




        
        

        
        
