---
- name: Configuración de Equipo
  hosts: oracle
  remote_user: root
  vars:
    - redhatpass: "$6$lf92fiDijp1G.mK6$plOZCrslpetoybLUIhs5jgfx2OqTvnl93/Tz0KgJavQtQq4u9TJJtYTzZmwu2Xi4oFy1S.MvjaRw.VU.r0fId/"
  tasks:
    - name: Install all my packages
      yum: name='@Server with GUI' state=lastest
      
    - name: Instalando paquetes para Oracle.
      yum: pkg={{item}} state=installed
      with_items:
        - tigervnc-server
        - xorg-x11-fonts-Type1
    - name: Creando usuario Red Hat.
      user:
        name: redhat
        password: '{{ redhatpass }}'
        
    - copy:
        src: /lib/systemd/system/vncserver@.service
        dest: /etc/systemd/system/vncserver@:3.service
        owner: oracle
        remote_src: yes
        
        firewall-cmd --permanent --zone=public --add-port=5903/tcp
        firewall-cmd --reload
        
        systemctl daemon-reload
        systemctl start vncserver@:3.service
        systemctl enable vncserver@:3.service
        
        
        subscription-manager attach --pool=8a85f9815dbd9297015dbdb8186b428d 
        sudo subscription-manager repos --disable=* 
        sudo subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms
        yum update -y
        
        yum install \
        libguestfs \
        libguestfs-tools \
        libvirt-client \
        libvirt \
        libvirt-python \
        qemu-guest-agent \
        qemu-img \
        qemu-kvm \
        virt-install \
        virt-manager \      
        virt-viewer \
        virt-who \
        spice-vdagent \
        targetcli \
        
        cd /var/lib/libvirt/images
        

        
        